#!/bin/sh
# Emit the fixed native v4 price observations used by this offline example.
# Keeping the values in this script makes regeneration deterministic.
cat <<'EOF'
// What the rental house was worth, quarter by quarter.
// Native v4 price observations; generated by scripts/home-prices.sh.

2024-12-18 HOME = 372_000 USD
2025-03-31 HOME = 388_500 USD
2025-06-30 HOME = 405_000 USD
2025-09-30 HOME = 421_000 USD
2025-12-29 HOME = 431_500 USD
EOF
