SRC = "crates/session/src/"
MUTANTS = [
 ("arena-bucket-off-by-one", SRC+"texts.rs", "((top - FIRST_BITS) as usize, numbered - (1 << top))", "((top - FIRST_BITS) as usize + 1, numbered - (1 << top))"),
 ("arena-slot-shared", SRC+"texts.rs", "place(self.taken.fetch_add(1, Ordering::Relaxed))", "place(self.taken.load(Ordering::Relaxed))"),
 ("arena-slot-zero", SRC+"texts.rs", "((top - FIRST_BITS) as usize, numbered - (1 << top))", "((top - FIRST_BITS) as usize, 0)"),
 ("table-replaces-first", SRC+"sources.rs", "next.files[usize::from(file.id.0)] = file;", "next.files[0] = file;"),
 ("project-paths-include-embedded", SRC+"sources.rs", "self.files.iter().filter(|file| !file.embedded).map(|&file| &*file.path)", "self.files.iter().map(|&file| &*file.path)"),
 ("get-skips-auxiliary", SRC+"sources.rs", "self.files.get(index).or_else(|| self.auxiliary.get(index.checked_sub(self.files.len())?)).copied()", "self.files.get(index).copied()"),
 ("replace-no-backwards-check", SRC+"edit.rs", "if start > end {\n                    return Err(Refused::NotSpan(*at));\n                }", ""),
 ("replace-tail-off-by-one", SRC+"edit.rs", "text.get(end..)", "text.get(end + 1..)"),
 ("replace-keeps-range", SRC+"edit.rs", "Ok([head, with, tail].concat())", "Ok([head, \"\", tail].concat())"),
 ("append-always-newline", SRC+"edit.rs", "let ended = text.is_empty() || text.ends_with('\\n');", "let ended = false;"),
 ("append-never-closes", SRC+"edit.rs", "let closed = lines.is_empty() || lines.ends_with('\\n');", "let closed = true;"),
 ("introduced-as-a-set", SRC+"edit.rs", "*had.entry(said(found)).or_default() += 1;", "*had.entry(said(found)).or_default() = 1000;"),
 ("introduced-ignores-code", SRC+"edit.rs", "(found.severity, found.code.as_ref(), found.message.as_str())", "(found.severity, \"\", found.message.as_str())"),
 ("between-swapped", SRC+"edit.rs", "let added = introduced(after.diagnostics(), before.diagnostics());\n        let removed = introduced(before.diagnostics(), after.diagnostics());", "let removed = introduced(after.diagnostics(), before.diagnostics());\n        let added = introduced(before.diagnostics(), after.diagnostics());"),
 ("json-drops-removed", SRC+"edit.rs", "[(\"added\", &self.added), (\"removed\", &self.removed)]", "[(\"added\", &self.added)]"),
 ("syntax-check-skipped", SRC+"session.rs", "if worse.is_empty() { Ok(edited) }", "if true { Ok(edited) }"),
 ("embedded-check-skipped", SRC+"session.rs", "if file.embedded {", "if false {"),
 ("apply-forgets-to-replace", SRC+"session.rs", "        *self = next;\n        Ok(applied)", "        let _ = next;\n        Ok(applied)"),
 ("what-if-keeps-text", SRC+"session.rs", "let hypothetical = Session::open(self.sources.with(&edited), self.options);", "let hypothetical = Session::open(self.sources.with(self.sources.texts().keep(edited.reading(edited.text.to_string()))), self.options);"),
 ("diagnostics-run-first", SRC+"session.rs", "self.book_diagnostics().iter().chain(self.run_diagnostics())", "self.run_diagnostics().iter().chain(self.book_diagnostics())"),
 ("query-ignores-whose", SRC+"session.rs", "Context::over(plan, folded, whose)?", "Context::over(plan, folded, None)?"),
 ("apply-wrong-file-reported", SRC+"session.rs", "Applied::between(kept.id, self, &next)", "Applied::between(axiom_core::FileId(0), self, &next)"),
 ("word-allows-empty", SRC+"transaction.rs", "let starts = text.bytes().next().is_some_and(|byte| byte.is_ascii_alphanumeric());", "let starts = true;"),
 ("amount-no-zero-pad", SRC+"transaction.rs", "format!(\"{units}.{quanta:0scale$}\")", "format!(\"{units}.{quanta}\")"),
 ("quote-no-escape", SRC+"transaction.rs", "'\"' => line.push_str(\"\\\\\\\"\"),", "'\"' => line.push('\"'),"),
 ("tail-codes-first", SRC+"transaction.rs", "        if let Some(purpose) = self.purpose {\n            let _ = write!(line, \" #{}\", word(purpose)?);\n        }", "        for code in self.codes {\n            let _ = write!(line, \" ^{}\", word(code)?);\n        }\n        if let Some(purpose) = self.purpose {\n            let _ = write!(line, \" #{}\", word(purpose)?);\n        }"),
 ("negative-allowed", SRC+"transaction.rs", "if money.qty.is_negative() {", "if false {"),
]
